/**
 * recetas.js — Lo que se hace en el fogon y en el patio.
 *
 * Todo lo que se cocina gasta lena, y casi todo gasta agua: por eso el juego
 * empieza yendo al rio. Anadir una receta es anadir una entrada aqui.
 */
export const RECETAS = [
  { id: 'tortilla', nombre: 'Tortillas', icono: '🫓', tipo: 'fogon',
    ingredientes: { maiz: 3, agua: 1 }, lena: 1, minutos: 40, xp: 8,
    produce: { id: 'tortilla', cantidad: 2 },
    descripcion: 'Nixtamal, molienda y comal. La comida de todos los días.' },
  { id: 'frijoles', nombre: 'Frijoles cocidos', icono: '🥣', tipo: 'fogon',
    ingredientes: { frijol: 3, agua: 2 }, lena: 2, minutos: 90, xp: 10,
    produce: { id: 'frijoles', cantidad: 2 } },
  { id: 'arroz_cocido', nombre: 'Arroz cocido', icono: '🍚', tipo: 'fogon',
    ingredientes: { arroz: 3, agua: 2 }, lena: 1, minutos: 45, xp: 10,
    produce: { id: 'arroz_cocido', cantidad: 2 } },
  { id: 'atole', nombre: 'Atole', icono: '🥤', tipo: 'fogon',
    ingredientes: { maiz: 2, agua: 2 }, lena: 1, minutos: 30, xp: 7,
    produce: { id: 'atole', cantidad: 2 } },
  { id: 'elote_asado', nombre: 'Elote asado', icono: '🌽', tipo: 'fogon',
    ingredientes: { maiz: 1 }, lena: 1, minutos: 15, xp: 4,
    produce: { id: 'elote_asado', cantidad: 1 } },
  { id: 'pescado_asado', nombre: 'Pescado asado', icono: '🐠', tipo: 'fogon',
    ingredientes: { pescado: 1 }, lena: 1, minutos: 20, xp: 8,
    produce: { id: 'pescado_asado', cantidad: 1 } },
  { id: 'carne_asada_venado', nombre: 'Carne asada', icono: '🍖', tipo: 'fogon',
    ingredientes: { carne_venado: 1 }, lena: 2, minutos: 35, xp: 12,
    produce: { id: 'carne_asada', cantidad: 2 } },
  { id: 'carne_asada_conejo', nombre: 'Conejo asado', icono: '🍖', tipo: 'fogon',
    ingredientes: { carne_conejo: 1 }, lena: 1, minutos: 25, xp: 9,
    produce: { id: 'carne_asada', cantidad: 1 } },
  { id: 'sopa', nombre: 'Sopa', icono: '🍲', tipo: 'fogon', requiere: 'cocina',
    ingredientes: { agua: 2, hierbas: 1, ayote: 1 }, lena: 2, minutos: 60, xp: 14,
    produce: { id: 'sopa', cantidad: 2 },
    descripcion: 'Con lo que haya: verdura, hierba y paciencia.' },
  { id: 'sopa_pescado', nombre: 'Sopa de pescado', icono: '🍲', tipo: 'fogon', requiere: 'cocina',
    ingredientes: { agua: 2, pescado: 1, hierbas: 1 }, lena: 2, minutos: 55, xp: 16,
    produce: { id: 'sopa', cantidad: 2 } },
  { id: 'pan', nombre: 'Pan', icono: '🍞', tipo: 'fogon', requiere: 'cocina',
    ingredientes: { trigo: 3, agua: 1 }, lena: 2, minutos: 80, xp: 18,
    produce: { id: 'pan', cantidad: 2 } },
  { id: 'pupusa', nombre: 'Pupusas', icono: '🥟', tipo: 'fogon', requiere: 'cocina',
    ingredientes: { maiz: 2, frijol: 1, agua: 1 }, lena: 1, minutos: 50, xp: 20,
    produce: { id: 'pupusa', cantidad: 2 },
    descripcion: 'Día de fiesta en la casa.' },
  { id: 'yuca_cocida', nombre: 'Yuca cocida', icono: '🥔', tipo: 'fogon',
    ingredientes: { yuca: 1, agua: 1 }, lena: 1, minutos: 35, xp: 6,
    produce: { id: 'sopa', cantidad: 1 } },

  // ------------------------------------------------------------- taller
  { id: 'rajar_lena', nombre: 'Rajar leña', icono: '🪓', tipo: 'taller',
    ingredientes: { tronco: 1 }, herramienta: 'machete', minutos: 20, xp: 6,
    produce: { id: 'lena', cantidad: 3 } },
  { id: 'pita', nombre: 'Torcer pita', icono: '🧵', tipo: 'taller', requiere: 'pita',
    ingredientes: { fibra: 3 }, minutos: 25, xp: 8,
    produce: { id: 'pita', cantidad: 1 } },
  { id: 'cana', nombre: 'Hacer una caña', icono: '🎣', tipo: 'taller',
    ingredientes: { pita: 1, fibra: 2 }, minutos: 40, xp: 14,
    produce: { id: 'cana', cantidad: 1 } },
  { id: 'hondilla', nombre: 'Hacer una hondilla', icono: '🪁', tipo: 'taller',
    ingredientes: { fibra: 3, piedra: 1 }, minutos: 30, xp: 12,
    produce: { id: 'hondilla', cantidad: 1 } },
  { id: 'trampa', nombre: 'Armar una trampa', icono: '🪤', tipo: 'taller', requiere: 'trampa',
    ingredientes: { pita: 2, fibra: 3 }, minutos: 35, xp: 14,
    produce: { id: 'trampa', cantidad: 1 } },
  { id: 'atarraya', nombre: 'Tejer la atarraya', icono: '🕸️', tipo: 'taller', requiere: 'atarraya',
    ingredientes: { pita: 6, fibra: 8 }, minutos: 180, xp: 40,
    produce: { id: 'atarraya', cantidad: 1 } },
  { id: 'cantaro', nombre: 'Hacer un cántaro', icono: '🏺', tipo: 'taller', requiere: 'barro',
    ingredientes: { barro: 4 }, lena: 2, minutos: 120, xp: 26,
    produce: { id: 'cantaro', cantidad: 1 } },
  { id: 'canasta', nombre: 'Tejer una canasta', icono: '🧺', tipo: 'taller',
    ingredientes: { fibra: 8 }, minutos: 70, xp: 18,
    produce: { id: 'canasta', cantidad: 1 } },
  { id: 'candil', nombre: 'Hacer un candil', icono: '🕯️', tipo: 'taller',
    ingredientes: { barro: 2, ocote: 2, fibra: 1 }, minutos: 45, xp: 16,
    produce: { id: 'candil', cantidad: 1 } },
];

export function receta(id) { return RECETAS.find((r) => r.id === id) || null; }
export function recetasDe(tipo) { return RECETAS.filter((r) => r.tipo === tipo); }
